### ISSUE TITLE
[ERROR] Bad function pointer: GetMapAuthor

### ISSUE THREAD

**Issue by dahn-d** [springweblobby/swl-website#100]
rekt
```
[ERROR]   Bad function pointer: GetMapAuthor
terminate called after throwing an instance of 'UnitsyncHandlerAsync::bad_fptr'
  what():  Symbol GetMapAuthor not found in the unitsync library.
fish: “./weblobby” terminated by signal SIGABRT (Abort)
```
when entered a host and it has finished the missing map download or entered the host with downloaded map

**Comment by DeinFreund** [comment]
Did you install a fresh weblobby and join one of the dev engine rooms? That's a known issue with the unitsync being bork. Workaround is first joining a room with 103.0 and then proceeding to use dev engine.

**Comment by dahn-d** [comment]
@DeinFreund, thanks for fast response, I appreciate it a lot! solved.

**Comment by dahn-d** [comment]
for reference, if no room with 103.0 available, then Downloads -> Add manually -> Engine -> 103.0
