### ISSUE TITLE
Fix «show games not selected in settings»

### ISSUE THREAD

**Issue by FabriceFABS** [springweblobby/swl-website#102]
In [BATTLES], when you have «Show games not selected in settings» enabled, you jump in the [CHAT] tab and you go back in [BATTLES] tab : Show games not selected in settings is not checked anymore :dagger: 
Thx...

**Comment by DeinFreund** [comment]
It's not only that, the whole state of the screen is reset. (That includes Matchmaker/Room creation settings)

**Comment by FabriceFABS** [comment]
Humm... alright.
Maybe by adding all MOD ( #103 ), then the reset of this setting become less important.
>

**Comment by db81** [comment]
Yeah we should cache the state somewhere.

**Comment by FabriceFABS** [comment]
Thank you !
