### ISSUE TITLE
New MOD to add in settings / Games to show...

### ISSUE THREAD

**Issue by FabriceFABS** [springweblobby/swl-website#103]
Would you be kind to add « Planet Annihilation » MOD ?
Thx

**Comment by DeinFreund** [comment]
Would it maybe make more sense to add a switch to permanently disable mod filtering? There are probably a lot of other small mods that are missed.

**Comment by FabriceFABS** [comment]
«Quickly» BIS : Would you be kind again to add « Planet Defense » MOD (it's Defense version of Planet Annihilation) ?

**Comment by FabriceFABS** [comment]
Thx !
