### ISSUE TITLE
Links doesn't work

### ISSUE THREAD

**Issue by FabriceFABS** [springweblobby/swl-website#111]
Nothing happens when you clic on a link, from any window.
The only way is to do is a copy-paste.... A bit boring as you may guess it.

Can you fix it ? :-)

**Comment by db81** [comment]
Is that new? Have they ever worked? Do they stop working randomly?

There's a quirk with Qt that makes links stop working sometimes. I'm not sure if there's a system to the madness but I think at least it stops working if you restart the browser while swl is open. Maybe it only works if the browser is already open when swl starts.

**Comment by FabriceFABS** [comment]
I'm quite sure links worked in the past.
I precise you I'm under Linux, if this can help.

**Comment by db81** [comment]
Yeah I think that's just the quirk. I don't think I've ever seen it on windows. I'm not going to try fixing Qt, but when I get around to finish the CEF rewrite I'll have to reimplement that without Qt anyway, and hopefully I'll do a better job.

**Comment by FabriceFABS** [comment]
You fixed it ?
Seems all working actually...

**Comment by db81** [comment]
Like I said, it fails randomly sometimes but usually works.
