### ISSUE TITLE
New MOD to add in settings / Games to show...

### ISSUE THREAD

**Issue by FabriceFABS** [springweblobby/swl-website#116]
Would you be kind to add « Phoenix Annihilation » MOD ? Thx

**Comment by FabriceFABS** [comment]
Up...
Can you make it plz ?
Just this is "annoying" because when you switch between [BATTLES] and [CHAT] tabs, the checked "Show games not selected in settings" disappear...

**Comment by db81** [comment]
Ah, sorry, forgot about this.
