### ISSUE TITLE
Multiplayer battle room is always Spring 96.0

### ISSUE THREAD

**Issue by AppSynergy** [springweblobby/swl-website#21]
N.B. Since I upgraded to Ubuntu 14.04, I've had very little luck getting SWL to behave itself.
I had some time today, and tried to identify and resolve as many of issues as I could.
I deleted and rebuild SWL before identifying these issues. These issues may well be related.

If I `Create Multiplayer Battle Room`, and choose a spring version other than 96.0  (91.0, for example) in `Show Advanced Options`, the game opens showing `Engine version 96.0`.

This happens even with fictional spring versions, e.g. `Foo`.

**Comment by AppSynergy** [comment]
N.B. I don't think this is an issue any more with the way **Custom skirmish** now works

**Comment by db81** [comment]
It was about Springie hosts though, custom skirmish is local. We could use an UI to spawn springies so you don't have to ```/msg Springiee !spawn mod=zk:stable,title=Cool room,password=secret```, old swl used to have that.
