### ISSUE TITLE
ReactJS weblobby on windows cannot find maps/games

### ISSUE THREAD

**Issue by blah1** [springweblobby/swl-website#27]
Steps to reproduce: 0. (Have games, maps, and engines already in %SpringHome%\Games, %SpringHome%\Maps, and %SpringHome%\weblobby\engines beforehand because ReactJS weblobby lacks download support at the moment. [%SpringHome% refers to the variable in swlrc, not an environment variable])
1. Load up ReactJS weblobby (using the -url option to use ReactJS weblobby instead of the default) and connect to a server
2. Join a multiplayer game with a game, map, and engine that you already have
Expected Result: You are able to join the match because you have the map and game
Actual result: RJS-SWL says that you are missing the map and game, although you have the engine, listing you as unsynced

In more detail, my spring\weblobby\engines folder has 98.0.1-396, 98.0.1-398, and 98.0.1-402 (I can't run engine 88, 91, or 94 apparently, so I deleted them, but that's a different story), and I'm trying to connect to a match that is using 98.0.1-398. Strangely enough, it's fixed if I move the Spring\packages and Spring\maps folders into 98.0.1-402 (yes, 402, not 398) (or symlink them with mklink /D like I did). 

I suspect that this is caused by the unitsync calls only checking in that engine's directory. (Here's where I labeled it as a windows thing, from talking with Anarchid it seems that this doesn't happen on linux and I don't know if unitsync.dll has different calls than unitsync.so, but take this with a pound of salt since I haven't looked into unitsync.) It seems that it only uses the last engine's unitsync, so I'm guessing that there's some global unitsync variable that is overwritten whenever a new engine is added (I blame "this.unitsync = new Unitsync..." from line 137 of store/GameInfoImpl.js).

**Comment by db81** [comment]
Can you try again after restarting? It should honor swlrc now.
