### ISSUE TITLE
ReactJS Fork: Ghosted users from nightwatch backlog

### ISSUE THREAD

**Issue by wagonrepairer** [springweblobby/swl-website#28]
When subscribed to a channel, joining, Nightwatch shows a message for a user not currently in a channel, it appears that the user is now in the channel list, without the flag.

**Comment by db81** [comment]
I can't reproduce, and Nightwatch store can't affect channel user lists. Are you sure it's nightwatch backlog? There's a known zk server bug where it reports users being in a channel incorrectly, @Anarchid said #zkadmin was particularly susceptible.

**Comment by wagonrepairer** [comment]
Oh if it's ZK server's fault then that would explain what I'm seeing. This could probably be closed, unless we want to tackle the server bug from the client side (if it's not too much effort of course). The ghost users can be identified due to lack of flag.

**Comment by db81** [comment]
Also note that prior to ZeroK-RTS/Zero-K-Infrastructure#590 users could lack the flag because the server failed to report their country.

I don't know if solving this client-side is possible and I'm not even sure what happens exactly. If I knew the cause I'd rather fix the server.
