### ISSUE TITLE
enhancement: Put battlelist button somewhere else

### ISSUE THREAD

**Issue by Rocavall** [springweblobby/swl-website#30]
In all the other lobbies I can check the other rooms fast in 1 click, while in this one I have to go through the home page if I want to do that (2 clicks). It is fine if you like staying in the same room all day, but I tend to check other rooms pretty often and I find it annoying.
EDIT: How the hell do I put those fancy labels?

**Comment by Anarchid** [comment]
Which fancy labels?

**Comment by Rocavall** [comment]
"Anarchid added the enhancement label 14 minutes ago"
that one

**Comment by Anarchid** [comment]
You need direct commit privs for that, i think. Ask your local direct commit privilege granting committee.

**Comment by db81** [comment]
You can go back to the battles tab in one click once you open it with the new tab layout.
