### ISSUE TITLE
enhancement: autoconnect option and default lobby

### ISSUE THREAD

**Issue by Rocavall** [springweblobby/swl-website#34]
Every time I start lobby I have to click the reactSWL button and then click the connect button. I don't like that. I'm a lazy person.

**Comment by Anarchid** [comment]
Fix the first part as follows: edit your launcher so that works something looks like this:
`/home/rocavall/Programs/weblobby/weblobby -url http://weblobby.springrts.com/reactjs/index.html`

**Comment by db81** [comment]
Making rswl default would require having engine options UI for feature parity with dojoswl and a bit of UI redesign to get rid of the evo and zk menus and make it generic. And then finally at least basic UI for evo, which requires turning rswl into a lib first. So not gonna happen right now.
