### ISSUE TITLE
Checkboxes became super thin so that whether they are checked or not cannot be seen

### ISSUE THREAD

**Issue by CommonPlayer** [springweblobby/swl-website#51]
![image](https://cloud.githubusercontent.com/assets/8286081/12656815/295936d6-c63b-11e5-8acb-a170dd53920c.png)

**Comment by db81** [comment]
Check (heh) if it works now.

**Comment by ForbodingAngel** [comment]
Apparently they are still inoperable: http://steamcommunity.com/app/291150/discussions/0/41973820442079715/

**Comment by db81** [comment]
Seems to be fixed.
