### ISSUE TITLE
Background image doesn't exist (trivial)

### ISSUE THREAD

**Issue by AppSynergy** [springweblobby/swl-website#56]
https://github.com/springweblobby/swl-website/blob/749f43675bc487336a975d8f1434a1fcb715e8b8/style/Home.sass#L69

**Comment by AppSynergy** [comment]
Btw, loving the improvements since I was last here 2(?) years ago!

**Comment by db81** [comment]
Yeah I meant to pick a new one but couldn't find a good one on evo site at the time. Feel free to suggest something.

Glad you like the new dojoless incarnation, I was kinda thinking about your disgust at the inline styles. etc when working on it.

**Comment by AppSynergy** [comment]
Code quality looking great.  Sass + npm + react for win.  Proud to have I think to have introduced sass to the project, now it's all sass!

This project's codebase and build/dev system now looks basically like one of my web dev projects, so I'm psyched about making some contribs again.
