### ISSUE TITLE
Battle list are not updated correcly

### ISSUE THREAD

**Issue by FabriceFABS** [springweblobby/swl-website#57]
Players that hosts games seems affect battles refresh list : We should quit SWL to get right battle list in such cases.
Have a look : https://youtu.be/7vFSRu9DhNE

We can also press F5 key but it closes all the non-favorite chats previously opened and kicks you out of a current game.

**Comment by db81** [comment]
More examples:
![](https://i.imgur.com/2y4voyJ.png)
http://pastebin.com/mRMgydY0
