### ISSUE TITLE
Dev only - unable to connect to server

### ISSUE THREAD

**Issue by AppSynergy** [springweblobby/swl-website#59]
When I `npm run build/watch`,  no websocket connection is established.

Any ideas?

**Comment by db81** [comment]
You mean when you run it in a browser? ZK lobby server used to allow websocket connections, but it had an interesting property of crashing the entire server whenever someone connected from Firefox, so it was abolished. I never bothered trying to fix that, instead I run a websocket bridge on a VPS I own. It's ```ws://torq.tk:8260``` if you want to use it (put this in custom lobby server in settings).

**Comment by AppSynergy** [comment]
Ah. I was going by `browserDemoWarning`

> This is a browser demonstration. While you can connect to the server and chat and join battles...

Anyway - sweet, thanks.
