### ISSUE TITLE
UI - infobox - find the join button

### ISSUE THREAD

**Issue by AppSynergy** [springweblobby/swl-website#60]
When there's lots of players &&/|| lots of battle metadata, the join button escapes off the bottom. 

![joinbtn](https://cloud.githubusercontent.com/assets/3657244/17079863/2579784a-5115-11e6-937d-dc99846b825f.png)

I'm thinking maybe:

+ move the join button to the top?
+ or it could be fixed position at the bottom
+ and/or definition list take up less vertical space...

![joinbtn_new](https://cloud.githubusercontent.com/assets/3657244/17079887/86cb2684-5115-11e6-8646-2df4d2c904b0.png)

WIP. Any thoughts?

**Comment by db81** [comment]
My vision was that the join button would stick at the bottom and the player list would get smaller to give space to metadata. QtWebKit should support flexboxes, so can probably be done with that, or even vanilla CSS somehow.

**Comment by AppSynergy** [comment]
https://github.com/springweblobby/swl-website/pull/61
