### ISSUE TITLE
Sorting favorite channels

### ISSUE THREAD

**Issue by FabriceFABS** [springweblobby/swl-website#65]
I like the feature to keep private channels opens and the fact that there is no difference between "chat" channels and channels like #main and others.
However, is it possible to sort them by alphabetical ?

**Comment by db81** [comment]
Does sorting them manually in settings work? I don't think there should be forced sorting and people are unlikely to have so many autojoin channels that they can't sort them manually.

**Comment by FabriceFABS** [comment]
Sorry I ignore it is possible.
Where is the button for sort it ?

**Comment by db81** [comment]
There's no button, I meant rearranging the lines in the textbox by hand.

**Comment by FabriceFABS** [comment]
Sorry, I tried many times, I don't know how to move them.
Would you be kind to tell me how to do it so ?

**Comment by db81** [comment]
```Settings``` → ```Chat``` → ```Autojoin channels/private messages```, it has a multiline text box. One line per channel. You rearrange the lines like you would in any text editor.

Select the line, press <kbd>CTRL</kbd>+<kbd>X</kbd> to cut it, <kbd>Backspace</kbd> to remove the leftover newline, arrow keys to navigate to where you want it to be, <kbd>Enter</kbd> to add a newline, <kbd>CTRL</kbd>+<kbd>V</kbd> to paste.

**Comment by FabriceFABS** [comment]
Oh !!
Thank you...
