### ISSUE TITLE
Zero-K Infrastructure - Breaking Changes

### ISSUE THREAD

**Issue by AppSynergy** [springweblobby/swl-website#75]
Note quite a few. So far I've spotted:

- _Minor_ - vote widget does not appear (you can still `!y`)
- _Major_ - cannot join teams (whilst spectator)
- _Critical_ - cannot connect to games   (connecting to 0.0.0.0 :0)

which is going to be tricky, b/c a lot of stuff [has moved to the server](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/tree/master/ZkLobbyServer) from the client in ZKL, and I've no idea how interdependent they are now...

**Comment by db81** [comment]
@Anarchid made the first step in 37fb51788ff772dcca6.

**Comment by AppSynergy** [comment]
Awesome.  Anything I can help with?

**Comment by Anarchid** [comment]
> Awesome. Anything I can help with?

Imo first thing would be to implement RequestConnectSpring to make rejoin work (lobby should send this message when you click the start button while game is already running). Afaict then server will send the already implemented ConnectSpring message and we'll have working rejoin. See info at https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Shared/LobbyClient/Protocol/Messages.cs for reference.

Also maybe useful https://github.com/Spring-Chobby/Chobby/commit/10dc6e5caa69ff938d8c56c0dab9a20d48dff2bf and https://github.com/Spring-Chobby/Chobby/commit/3598d94b07ae74f83de185aadd13e8f13f86e290

**Comment by db81** [comment]
Connecting to games works now. Only need an UI for OpenBattle.

**Comment by db81** [comment]
Also the vote bar is broken.

**Comment by DeinFreund** [comment]
Open Battle and Battle Running status should be working. Votes?

**Comment by DeinFreund** [comment]
Matchmaking still needs a proper status display. I thought about a new Tab but I guess that'd be overkill.

**Comment by db81** [comment]
I'm thinking a status label in the battle tab.

**Comment by Anarchid** [comment]
I think matchmaking status UI can be another issue. Close?

**Comment by db81** [comment]
Dein added status UI.
