### ISSUE TITLE
"Freeze" when trying to join battle

### ISSUE THREAD

**Issue by DeinFreund** [springweblobby/swl-website#82]
> [WARNING] undefined:69 TypeError: undefined is not an object (evaluating 'data.users[data.currentBattle.founder].inGame')

(MBattle.js:69)
This warning spammed the console until overflow.

I expected the !! to deal with any undefined problems?

**Comment by db81** [comment]
That's what e2ccf4ce8b53bb23ca7 was made to fix. The logic was wrong so if the battle wasn't running and the original founder had disconnected it would spam this exception.

**Comment by DeinFreund** [comment]
Sry, nvm then. Still running an old branch :|
