### ISSUE TITLE
SWL doesn't properly download/run spring dev builds.

### ISSUE THREAD

**Issue by DeinFreund** [springweblobby/swl-website#91]
Downloads as 103.0.1-124-g976888c develop
Tries to execute as 103.0.1-124-g976888c

**Comment by DeinFreund** [comment]
https://github.com/springweblobby/swl-website/blob/master/store/ZkLobbyServer.js#L465

Could add " develop" to end of engine version string if it's a dev engine.

**Comment by Anarchid** [comment]
That's what is already being done during download, and is why downloads succeed. I guess since ZK seems to keep this naming scheme, makes sense to reuse that logic.

**Comment by DeinFreund** [comment]
Why isn't it limited to zkls there?

**Comment by db81** [comment]
I don't remember but it was either just in case, or it was added before zkls split.

**Comment by db81** [comment]
Blindfoxed by @Anarchid.
