### ISSUE TITLE
Breaking changes in unitsync

### ISSUE THREAD

**Issue by mtroyka** [springweblobby/swl-website#96]
log: http://pastebin.com/TPmLhx1x

Running windows 7

**Comment by Anarchid** [comment]
Investigation yielded info:
- 103.0 works
- 103-129 launched directly works
- local games using 103-129 crash with same error

Remaining hypotheses: broken engine download or 103-129 unitsync broken on this OS

**Comment by db81** [comment]
Some deprecated unitsync functions were removed from the latest dev engine versions. For now just download 101.0 as a workaround (open downloads and click add manually)

**Comment by mtroyka** [comment]
After testing that's what I'd begun to suspect. Go figure.
