### ISSUE TITLE
Map is not displayed anymore

### ISSUE THREAD

**Issue by FabriceFABS** [springweblobby/swl-website#99]
... Seems from yesterday.
Also after a restart of SWL, F5, and PC reboot.

![map](https://cloud.githubusercontent.com/assets/6024913/19066049/7ab0118a-8a17-11e6-92c9-9738acbb9697.png)

**Comment by db81** [comment]
That's because SpringFiles is down. I can't control that.

**Comment by FabriceFABS** [comment]
OK sorry didn't think it was related to.
++
